package com.example.travelplanner.fragments;
import android.app.Dialog;
import android.os.Bundle;

import androidx.fragment.app.Fragment;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.example.travelplanner.R;
import com.example.travelplanner.adapters.DestinationAdapter;
import com.example.travelplanner.adapters.DestinationAdapter2;
import com.example.travelplanner.data.Destination;
import com.example.travelplanner.data.Destination2;

import java.util.ArrayList;
import java.util.List;

public class HomeFragment extends Fragment {
    private List<Destination> destinationList;
    private List<Destination2> destinationList2;
    public Dialog featuresDialog;
    DestinationAdapter dadapter;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_home, container, false);
        // Initialize your static destination data
        destinationList = createStaticDestinationList();
        destinationList2 = createIndianStateDestinationList();
        featuresDialog = new Dialog(getActivity());
        featuresDialog.setContentView(R.layout.dialog_features);

        RecyclerView recyclerView = view.findViewById(R.id.homeRecyclerView);
        RecyclerView recyclerView1 = view.findViewById(R.id.home2RecyclerView);
        recyclerView.setLayoutManager(new LinearLayoutManager(getActivity(), LinearLayoutManager.HORIZONTAL, false)); // Add this line
        recyclerView1.setLayoutManager(new LinearLayoutManager(getActivity(), LinearLayoutManager.HORIZONTAL, false));
        DestinationAdapter adapter = new DestinationAdapter(requireContext(), destinationList);
        DestinationAdapter2 adapter2 = new DestinationAdapter2(requireContext(), destinationList2);
        recyclerView.setAdapter(adapter);
        recyclerView1.setAdapter(adapter2);
        return view;
    }

    private List<Destination> createStaticDestinationList() {
        List<Destination> destinations = new ArrayList<>();
        destinations.add(new Destination("Singapore", "Singapore is a country that celebrates colorful culture. Take the best budget foreign trips to Singapore in 2023 and make loads of memories.A tiny yet modern country offers great bargains and is a wise way to spend money on a vacation.", R.drawable.singapore, "INR 42,000", "Singapore is a country that celebrates colorful culture. Take the best budget foreign trips to Singapore in 2023 and make loads of memories. A tiny yet modern country offers great bargains and is a wise way to spend money on a vacation. If you still haven’t explored Singapore then this your time to plan a budget international trip and visit this country. With an extensive number of futuristic places to witness and some cherishable experiences to behold, Singapore is one destination that never fails to impress. All of this is exactly what makes Singapore the best of international tours that one can take in this year! Don’t forget to indulge in free things to do in Singapore to save additional expenses.", "Singapore: Trip Starting From INR 42,000", "The round trip flight tickets can cost between INR 20,000 – 22,000 onwards if boarding from New Delhi or Mumbai or INR 11,000 – 15000 From Chennai or Kolkata", "Singapore offers accommodation options like the City Backpackers @ Kallang or Fernloft City Hostel which offers stay for as low as INR 600/ night. On the other hand, a single room can start from INR 2000/ night in a decent budget hotel", "Chinatown food center, Maxwell food center or any hawker center are the places where you can get a meal in less than INR 500 inclusive of main, drink, and dessert", "Singapore is famous as a holiday destination either for its day excursions or Singapore cruises. Either way don’t miss out on the Singapore tourist attractions like the famous National Museum of Singapore or Orchard Road/ Dhoby Ghaut Shopping stretch. Must Visit include Underwater World, Dolphin Lagoon", " 4 Days and 3 Nights", "Approx. INR 42,000", "Explore Singapore at night when it is beautifully light up with the iconic Marina Bay Sands hotel and Singapore flyer view", "February-April", "The international airport of Singapore – Changi Airport is well-connected with all the major parts of the country. Taking a flight to Singapore is the best way to reach this destination", " Singapore Dollars", "English, Malay, Tamil, Mandarin Chinese","Singapore"));
        destinations.add(new Destination("Malaysia", "There are numerous exciting things to do in Malaysia that will make you have the best time here! Think of Malaysia for budget foreign trips and you shall begin to imagine turquoise waters, stunning beaches and pleasant climate.", R.drawable.malaysia, "INR 40,000", "There are numerous exciting things to do in Malaysia that will make you have the best time here! Think of Malaysia for budget foreign trips and you shall begin to imagine turquoise waters, stunning beaches and pleasant climate. One of the major tourist hub in Southeast Asia, Malaysia is the perfect picturesque destination you’d been waiting for and where you can plan a low budget international trip from India. For those who are in search of international trips under 1 lakh should surely consider visiting Malaysia. This destination has plenty to offer well under the budget! Also, make sure you plan your trip during the months when in festivals in Malaysia take place!", "Malaysia: Trip Starting From INR 40,000", "A round trip could start from INR 20,000 onwards", "You can easily find guesthouses or dormitory rooms in Kuala Lumpur starting for as low as INR 300 per night", "Track down places in Kuala Lumpur like Nasi Kandar Pelita, Saravanaa Bhavan, Taman Paramount Night market and so on", "Kuala Lumpur, Sarawak, Pangkor, Redang Island and others places are must visit in Malaysia. While top most things to do are – Day tour to Elephant Orphanage Sanctuary, dinner along Singapore River, Chinatown Trishaw night tour, Batu Caves and temple tour, Petronas Towers", " 4 Days and 3 Nights", "Approx. INR 40,000", "Malaysia is a Muslim country and drinking is frowned upon, so drinking is both restrictive and expensive. Save your drinking for a better budget country.", "December-February", "The best and the only way to reach Malaysia from India is by taking a flight. There are regular flights flying to and fro Kuala Lumpur International Airport. Air Asia and Malaysian Airlines are the best airlines to book", "Malaysian Ringgit", "Malay","Kuala Lumpur"));
        destinations.add(new Destination("Thailand", "Topping the charts is the world-renowned destination – Thailand. Indulge in its beaches, mountains, culture, food, and more. And the best part is, it is one of the cheap international destinations from India that fits just within the budget for all.", R.drawable.thailand, "INR 35000", "Topping the charts is the world-renowned destination – Thailand. Indulge in its beaches, mountains, culture, food, and more. And the best part is, it is one of the cheap international destinations from India that fits just within the budget for all. It is one of the most cheap foreign trips from India. From adventure enthusiasts to leisure seekers, Thailand offers one of those international trips under 30k from India that is for every kind of traveler.", "Thailand: Trip Starting From INR 35,000", "Thailand: Trip Starting From INR 35,000", "Whether you are traveling in a group or solo, Thailand is full of budget staying options starting from as low as INR 573 per night per person. You can choose from a dormitory type accommodation, a hostel or even a decent budget hotel", "Thailand is famous for its street food. A good budget meal can cost up to approximately INR 60", "A combination of any 2-3 cities like Bangkok, Pattaya and coral islands, Ayutthaya, Chiang Mai is a good option to explore the culture of Thailand. Almost every city will be home to few of the many Ancient Buddha temples, Pattaya floating markets, elephant show and so on", "6 Days and 5 Nights", "Approx. INR 35,000", "Explore the “tuk-tuk ride”, underwater world, floating market, Thailand’s famous “Som Tam” (Papaya Salad) and needless to say, the street shopping around Victoria’s monument in Bangkok", "November-April", "Thailand is home to two major airports – one in Bangkok and one in Phuket. Both the international airports connect Thailand to the major countries in the world. Thai Airways are the major airlines running in this nation", "Thai Baht", "Thai","Bangkok"));
        destinations.add(new Destination("Indonesia", "Rich in cultural heritage, visit Indonesia for its encouraging natural beauty bounded by much more! If you are looking for international trips under 1 lakh then Indonesia is one destination that you can surely consider.", R.drawable.indonesia, "INR 45000", "Rich in cultural heritage, visit Indonesia for its encouraging natural beauty bounded by much more! If you are looking for international trips under 1 lakh then Indonesia is one destination that you can surely consider! It is really is perfect for a low budget foreign trip. You could also plan your trip around the time of festivals in Indonesia for a unique cultural experience. Indonesia happens to be one of the best and cheap foreign trips from India without a visa. So travel to this beautiful destination of luxury and tranquility without any hassles!", "Indonesia: Trip Starting From INR 45,000", "Flight expenses for a round trip could cost you approx. INR 25000 and could be lesser if booked well in advance", "Hostels in Jakarta could cost INR 700 onwards per night", "Three square warung (food stall) meals can cost as little as INR 120 per meal. Dining in decent local restaurants could cost INR 500-600 per day", "Make sure to visit places like – Bali, Java, Yogyakarta, Jakarta, and Sumatra. Don’t miss out on things like Bali Village cycling tour, Spa treatments at places like Anika spa, water sports, and volcano tours", "5 Days and 4 Nights", "Approx. INR 45,000", "A shoestring traveler can spend as little as INR 800 per day and still explore the scenic island country! But confine yourself to selected cities as budget accommodation can be limited and also flying from one island to another is much more expensive", " May-September", "One can book a flight till  Soekarni-Hatta International Airport that is situated in Jakarta or head to Denpasar’s airport i.e. Ngurah Rai International Airport. It takes around 5 hours to cover the distance to Indonesia by airways", "Indonesian Rupiah", "Indonesian","Jakarta"));
        destinations.add(new Destination("Seychelles", "Seychelles Islands would totally fit your requirement if you want to plan a a low-budget foreign tour. Nested amidst the sparkling Indian Ocean, this African nation is essentially an archipelago formed by over 100 islands.", R.drawable.seychelles, "INR 40000", "Seychelles Islands would totally fit your requirement if you want to plan a a low-budget foreign tour. Nested amidst the sparkling Indian Ocean, this African nation is essentially an archipelago formed by over 100 islands. Famed for its boundless natural beauty and picture-perfect range of beaches, it is an ideal place to take budget international trips with your family or better half.", "Seychelles: Trip Starting From INR 40,000", "The round trip flight tickets from New Delhi could cost approx. INR 36,000 onwards", "Le Duc de Praslin, Chateau St Cloud, and Le Relax Hotel are some great options for those looking for affordable accommodation in Seychelles", "Bravo Restaurant, La Perle Noire Restaurant, Maria’s Rock Cafeteria, Chez Jules Restaurant, and many more", "Mahe Island, La Digue, Vallée de Mai, Anse Source d’Argent, Frégate Island, and more", "7 Days and 6 Nights", "Approx. INR 40,000", "Choose to travel around by bicycles to make sure you enjoy the natural beauty of this island nation to the fullest", "April-May, October-November", "Seychelles is home to two major airports named Seychelles International Airport and Praslin Island Airport. The best one is the former one as that is the entry point for international travelers. This is the busiest airport of this island nation", "Seychellois Rupee", "French, English, Seselwa","Victoria"));
        destinations.add(new Destination("Qatar", "The stunning beauty of the Persian Gulf, Qatar is a one of the most prismatic tourist destination amongst the Arab countries. If you still haven’t explored this place then make sure that you plan your next budget international trip to Qatar this year.", R.drawable.qatar, "INR 45000", "The stunning beauty of the Persian Gulf, Qatar is a one of the most prismatic tourist destination amongst the Arab countries. If you still haven’t explored this place then make sure that you plan your next budget international trip to Qatar this year. There are plenty of places to visit in Doha for a wonderful vacation. Qatar also happens to be one of the offbeat places to take an international trip that is not heavy on your pockets! It may not be on of the cheap international destinations but you can surely travel on a budget.", "Qatar: Trip Starting From INR 45,000", "While the tickets can cost you approximately INR 17000 if planned on time", "The accommodation could cost you approx INR 9000-10,000 for a 5 day stay in the country", "The must-visits include Doha, Dhal Al Misfir, Khor Al Adaid Natural Reserves and Zubarah Fort", "Things to do in the country include helicopter rides, beaches, dune bashing and camel rides", " 4 days and 3 nights", "Approx. INR 45,000", "December and January are the ideal months to explore the gulf area with milder, pleasant and chilly evenings", "April-May, September-October", "One can book their flight tickets to reach Qatar. Doha International Airport resides in the country and connects the country well to all the major parts of the world", "Qatari Riyal", "Arabic","Doha"));
        destinations.add(new Destination("UAE", "Another stunning beauty of the Arab word is the United Arab Emirates with Dubai as its most precious tourist jewel. A hub for international tourists, UAE is found in the bucket lists of several travelers.", R.drawable.uae, "INR 50000", "Another stunning beauty of the Arab word is the United Arab Emirates with Dubai as its most precious tourist jewel. A hub for international tourists, UAE is found in the bucket lists of several travelers. If you are one of them then this is the year when you can plan a budget international trip and explore the UAE. This land of Sheikhs hides attractions that never fail to inspire awe and blankets experiences that are nothing less than Royal! Dubai is indeed one of the cheapest countries to visit from India.", "United Arab Emirates: Trip Starting From INR 50,000", "The flight tickets start from approximately INR 12,000 depending on the time of the year", " At the same time, the accommodation in Dubai for backpackers could cost approximately INR 2000/ night", "For meals, a sprinkling of local knowledge could open plenty of budget-friendly options like Ravi in Al Satwa and Zaroob", "Indulge in city’s best views of Dubai Marina at night to the neck arching sight of Burj Khalifa", "The suggested time to spend your travel here is 5 nights", "Prepare to have a budget of INR 50,000 in the country", "Make use of Dubai’s recently invested rental bike scheme which allows you to rent sturdy bikes and save money on taxis", "October – April", "Although there are plenty of airports housing in UAE, the majore ones are Abu Dhabi International Airport, Al Ain International Airport, and the Dubai International Airport. There are direct flights that link UAE to the major countries all around the world", "Dirham", "Arabic","Dubai"));
        destinations.add(new Destination("Hong Kong", "he former British colony perched on the shore of South China Sea offers plenty of bargains despite being famous for its glitz lifestyle. Head here for a groovy and electrifying holiday experience.", R.drawable.hk, "INR 40000", "The former British colony perched on the shore of South China Sea offers plenty of bargains despite being famous for its glitz lifestyle. Head here for a groovy and electrifying holiday experience. Hong Kong is one of the best places when thinking of cheap international destinations from India so make sure that you explore it this year if you still haven’t.", "Hong Kong: Trip Starting From INR 40,000", "If booking with a time gap of fewer than 2 months, the round trip could cost approx. INR 27,000", "Hostels prices start around INR 700 per night at places like HK Downtown Backpackers", "While Hong Kong is generally expensive, one can save money while eating the market food, noodles, and dumplings which could cost less than INR 100 at Tim Ho Wan on 2-2 Kwong Wa Street, Mong Kok", "Include hike on the famous Dragon’s Back Trail, Avenue of the stars, Hong Kong Museum of Art (entry free on Wednesday). There are also plenty of day trips from Hong Kong that you could take on your vacation. Must visits include Lantau Island, Stanley Market, Cheung Chau island, Sai Kung", "5 Days and 4 Nights", "Approx. INR 40,000", "Explore the top shopping favorites – The Temple Street Night Market and HK’s Kitschy-cool street. For a better bargain try and say this: Tai Gwai la (It’s too expensive!)", "October-December", "Hong Kong International Airport is the most popular airport in this nation. There are direct flights such as Air India, Indigo, Cathay Pacific, and many more that operate to this destination", "Hong Kong Dollar", "Chinese, English","HongKong"));
        destinations.add(new Destination("Sri Lanka", "Sri Lanka is one of the most cheap foreign trips from India. Famous for being the best backpacking destination. Visit this home away from home that solves the purpose for those looking forward to cheap foreign trips from India.", R.drawable.srilanka, "INR 35000", "Sri Lanka is one of the most cheap foreign trips from India. Famous for being the best backpacking destination, it is home to landscapes and culture which is much like India. Visit this home away from home that solves the purpose for those looking forward to cheap foreign trips from India. It is one of the world’s cheapest countries to travel from India. With the fragrance of tea plantations encircling the atmosphere, lush green foliage covering the floors, and locals serving the mouth-watering dishes, Sri Lanka is a destination that takes away the breath of travelers!", " Sri Lanka: Trip Starting From INR 35,000", "The round trip flight tickets can cost:- From Delhi: INR 20,000 onwards From Chennai: INR 8000 onwards", "Colombo Sea view hostel, Colombo city hostel and so on are dormitory style accommodations that starts for INR 600/night. Similarly in other places like Kandy, Bentota and so on, hotel rooms can range from INR 1000 onwards per night", "Ceylon Tea Moments in Colombo is one of the top choices which offers a huge menu within the range of INR 100-500; A classic Sri Lankan meal of fish curry in local markets can cost you less than INR 100", "The must visit cities include Colombo, Kandy, Nuwara Eliya and Bentota. Also visit world heritage sites like Temple of tooth Relic, boating or fishing on Lake Gregory, tea factory visits, Seetha Eliya garden and temple from famous Ramayana, turtle hatchery etc. Visit Odel, Majestic city etc for shopping", "5 Days and 4 Nights", "Approx. INR 35,000", "“Aa-yu-bo-wan” is hello in the local language. Traveling on public transport such as buses and train is usually the choice which is both crowded as well as cheap!", "December to March for west coast, April-Septmeber for east coast", "The best and easiest way to reach Sri Lanka is by taking a flight till Bandaranaike Internal Airport. This airport is located in Colombo and is well-connected with the major parts of the world", "Sri Lankan Rupee", "Sinhala, Tamil","Colombo"));
        destinations.add(new Destination("Cambodia", "Cambodia is one of the most beautiful yet cheapest international destinations. The enchanting form of cultural heritage, the country of Cambodia will leave you wanting for more with its panoramic and rustic beauty.", R.drawable.cambodia, "INR 25000", "Cambodia is one of the most beautiful yet cheapest international destinations. The enchanting form of cultural heritage, the country of Cambodia will leave you wanting for more with its panoramic and rustic beauty. It is one of the most cheap foreign trips from India.", "Cambodia: Trip Starting From INR 25,000", "The country also known as “Kingdom of Wonder” can be experienced in a round trip of INR 25000 onwards", "Being a cheap travel destination, an ideal accommodation for backpackers could cost as little as INR 300 per day", "When traveling on a budget go for the Cambodian food which is far cheaper and always quite good", "The must-visits include Siem Reap, Phnom Penh, Otres beach and Kampot. You can travel in Cambodia on a budget of INR 2000 per day", "5 days and 4 nights", "Approx. INR 25,000", "Make sure to take a trip to the most popular beach in Cambodia- Sihanoukville. Attend the festivals in Cambodia for a vibrant experience", "November-April", "Phnom Penh International Airport is the major airport of Cambodia. One can easily take a flight till Cambodia from Bangkok, which is the most common way of reaching this destination", "Cambodia Riel", "Khmer","Phnom Penh"));
        destinations.add(new Destination("Vietnam", "Vietnam is indeed one of the best places for budget international trips. Shaped like the letter “S”, lying on the eastern part of Indo-Chinese peninsula is Vietnam. In the country you will find timeless charm which is why it is one of the best places to visit.", R.drawable.vietnam, "INR 40000", "Vietnam is indeed one of the best places for budget international trips. Shaped like the letter “S”, lying on the eastern part of Indo-Chinese peninsula is Vietnam. In the country you will find timeless charm, and a flavor of another Asian culture which is why it is one of the best places to visit in March outside India.", "Vietnam: Trip Starting From INR 40,000", "Round trip of INR 25000 onwards", "Being a cheap travel destination, an ideal accommodation for backpackers could cost as little as INR 300 per day", "When traveling on a budget go for the Cambodian food which is far cheaper and always quite good", "The must-visits include Siem Reap, Phnom Penh, Otres beach and Kampot. You can travel in Cambodia on a budget of INR 2000 per day", "5 days and 4 nights", "Approx. INR 25,000", "Make sure to take a trip to the most popular beach in Cambodia- Sihanoukville. Attend the festivals in Cambodia for a vibrant experienc", "November-April", "Phnom Penh International Airport is the major airport of Cambodia. One can easily take a flight till Cambodia from Bangkok, which is the most common way of reaching this destination", "Cambodia Riel", "Khmer","Hanoi"));
        return destinations;
    }

    private List<Destination2> createIndianStateDestinationList() {
        List<Destination2> destinations = new ArrayList<>();
        destinations.add(new Destination2("Goa", "Goa is a popular tourist destination known for its beautiful beaches and vibrant nightlife. It offers a perfect getaway for relaxation and water sports.", R.drawable.goa, "INR 15,000", "Explore the stunning beaches of Goa and indulge in water sports like parasailing and scuba diving.", "Goa: Hotels in the State Starting From INR 15,000", "Entry fees to some attractions may apply.", "You can find a variety of accommodations ranging from budget hotels to luxury resorts in Goa.", "Enjoy the delicious seafood and local Goan cuisine.", "Visit the historic forts, vibrant markets, and enjoy the nightlife.", "3-7 days", "Prices may vary based on your choices and the duration of your stay.", "Carry sunscreen and stay hydrated, especially during the hot season.", "Anytime, but the best time to visit is from October to March.", "The nearest airport to Goa is Dabolim Airport, and you can also reach Goa by train or road."));
        destinations.add(new Destination2("Kerala", "Kerala, known as 'God's Own Country,' offers lush green landscapes, backwaters, and rich cultural experiences.", R.drawable.kerela, "INR 20,000", "Experience the serene backwaters of Kerala by taking a houseboat ride.", "Kerala: Hotels in the State Starting From INR 20,000", "Entry fees may be applicable at some tourist spots.", "Various types of accommodations are available, including houseboats and eco-friendly resorts.", "Savor traditional Kerala cuisine, including dosa, idli, and seafood delicacies.", "Visit famous temples, spice gardens, and enjoy cultural performances.", "5-10 days", "Prices vary based on your choices and the duration of your stay.", "Carry insect repellent for backwater areas.", "Year-round, but the best time is from September to March.", "Kerala is well-connected by air, train, and road, with major airports in Kochi, Trivandrum, and Calicut."));
        destinations.add(new Destination2("Rajasthan", "Rajasthan, known for its rich heritage and royal palaces, offers a glimpse into India's history.", R.drawable.rajasthan, "INR 25,000", "Visit iconic destinations like Jaipur, Udaipur, Jodhpur, and Jaisalmer.", "Rajasthan: Hotels in the State Starting From INR 25,000", "Entry fees may apply at historical sites and palaces.", "You can find accommodations in heritage hotels, palaces, and modern hotels.", "Indulge in Rajasthani cuisine, which includes dal-bati-churma and various sweets.", "Explore majestic forts, palaces, and colorful markets.", "7-12 days", "Costs vary depending on accommodation choices and duration of stay.", "Carry a scarf and sunglasses for sun protection.", "Best visited between October to March.", "Rajasthan is well-connected by air, train, and road. Jaipur, Udaipur, and Jodhpur have major airports."));
        destinations.add(new Destination2("H.P", "Himachal Pradesh offers breathtaking landscapes, including the Himalayan mountains, lush valleys, and serene lakes.", R.drawable.himachal, "INR 18,000", "Go trekking in the Himalayas, visit Shimla and Manali.", "Himachal Pradesh: Hotels in the State Starting From INR 18,000", "National parks and adventure activities may have entry fees.", "Accommodations include hotels, guesthouses, and camping options in the hills.", "Try Himachali cuisine and street food like momos and chana chaat.", "Engage in adventure activities like paragliding and river rafting.", "5-10 days", "Expenses can vary based on accommodation and duration of stay.", "Pack warm clothing if traveling in winter.", "Visit during spring or summer for pleasant weather.", "The nearest airports are in Shimla, Kullu, and Dharamshala. You can also reach Himachal Pradesh by train or road."));
        destinations.add(new Destination2("Tamil Nadu", "Tamil Nadu is known for its rich cultural heritage and temples.", R.drawable.tamilnadu, "INR 15,000", "Visit famous temples like Meenakshi Amman Temple in Madurai, Brihadeeswara Temple in Thanjavur.", "Tamil Nadu: Hotels in the State Starting From INR 15,000", "Entry fees may be applicable at some temples and historical sites.", "Various types of accommodations are available, including hotels and homestays.", "Enjoy traditional South Indian cuisine, including dosa, idli, and filter coffee.", "Explore the ancient temples and vibrant traditions of the state.", "3-7 days", "Costs vary based on your accommodation choices and the duration of your stay.", "Carry comfortable walking shoes for temple visits.", "Year-round, but the best time to visit is from October to March.", "Tamil Nadu is well-connected by air, with major airports in Chennai, Madurai, and Coimbatore. You can also reach by train or road."));
        destinations.add(new Destination2("Uttarakhand", "Uttarakhand offers stunning natural beauty with the Himalayan range, pristine lakes, and lush forests.", R.drawable.uttarakhand, "INR 20,000", "Go trekking in the Himalayas, visit Rishikesh and Haridwar.", "Uttarakhand: Hotels in the State Starting From INR 20,000", "Entry fees apply to some adventure activities and national parks.", "Accommodations include hotels, resorts, and guesthouses in scenic locations.", "Relish local cuisine and street food, and enjoy the view.", "Engage in adventure activities and spiritual experiences.", "5-10 days", "Expenses vary based on your accommodation and duration of stay.", "Carry warm clothing, especially if visiting in winter.", "Best visited between March to June and September to November.", "The nearest airports are in Dehradun and Pantnagar. You can also reach Uttarakhand by train or road."));
        destinations.add(new Destination2("Maharashtra", "Maharashtra is a diverse state known for its bustling cities, historic sites, and scenic landscapes.", R.drawable.maharastra, "INR 20,000", "Discover the vibrant culture of Mumbai, explore the UNESCO World Heritage sites in Ajanta and Ellora.", "Maharashtra: Hotels in the State Starting From INR 20,000", "Entry fees apply to some historical sites and museums.", "Accommodations range from budget hotels to luxury options.", "Savor local Maharashtrian cuisine, including vada pav and bhakri.", "Explore the historic caves, vibrant markets, and enjoy the beaches.", "4-9 days", "Costs vary based on accommodation choices and the duration of your stay.", "Carry an umbrella during the monsoon season.", "Year-round, but the best time to visit is from October to March.", "Maharashtra is well-connected by air, with major airports in Mumbai, Pune, and Nagpur. You can also reach by train or road."));
        destinations.add(new Destination2("Gujarat", "Gujarat offers a blend of history, culture, and natural beauty.", R.drawable.gujrat, "INR 18,000", "Visit the White Desert of Rann of Kutch, experience the rich culture of Gujarat.", "Gujarat: Hotels in the State Starting From INR 18,000", "Entry fees may apply at historical sites and wildlife reserves.", "You can find accommodations in hotels and resorts with a range of facilities.", "Indulge in Gujarati cuisine, including dhokla and theplas.", "Explore the historic sites, wildlife sanctuaries, and cultural attractions.", "4-9 days", "Expenses vary based on your accommodation choices and the duration of your stay.", "Carry sun protection in the arid regions.", "Best visited between October to March.", "Gujarat is well-connected by air, with major airports in Ahmedabad, Vadodara, and Surat. You can also reach by train or road."));
        destinations.add(new Destination2("M.P", "Madhya Pradesh is known for its rich historical and cultural heritage.", R.drawable.madhyapradesh, "INR 22,000", "Visit Khajuraho temples, go on a wildlife safari in Kanha National Park.", "Madhya Pradesh: Hotels in the State Starting From INR 22,000", "Entry fees may apply to national parks and historical sites.", "Accommodations include hotels, jungle lodges, and heritage properties.", "Enjoy traditional Madhya Pradesh cuisine, including poha and kebabs.", "Explore ancient temples, historical cities, and wildlife sanctuaries.", "6-12 days", "Expenses vary based on your accommodation choices and the duration of your stay.", "Carry insect repellent for wildlife safaris.", "Best visited between October to March.", "Madhya Pradesh is well-connected by air, with major airports in Bhopal and Indore. You can also reach by train or road."));
        destinations.add(new Destination2("Assam", "Assam is known for its tea gardens, wildlife, and unique culture.", R.drawable.assam, "INR 19,000", "Go on a wildlife safari in Kaziranga, visit ancient temples.", "Assam: Hotels in the State Starting From INR 19,000", "Entry fees apply to national parks and some cultural attractions.", "Accommodations include hotels and tea garden bungalows.", "Savor Assamese cuisine and enjoy Assam tea.", "Explore wildlife sanctuaries, ancient temples, and the scenic tea gardens.", "5-10 days", "Expenses vary based on your accommodation choices and the duration of your stay.", "Carry binoculars for birdwatching in the national parks.", "Best visited between November to April.", "Assam is well-connected by air, with major airports in Guwahati and Dibrugarh. You can also reach by train or road."));
        destinations.add(new Destination2("Punjab", "Punjab is known for its rich cultural heritage, delicious Punjabi cuisine, and vibrant festivals.", R.drawable.punjab, "INR 15,000", "Visit the Golden Temple in Amritsar, explore historic sites in Patiala.", "Punjab: Hotels in the State Starting From INR 15,000", "Entry fees may apply at some historical sites and cultural attractions.", "Accommodations include hotels and guesthouses.", "Indulge in Punjabi cuisine, including butter chicken and sarson da saag.", "Experience the rich culture, visit historic sites, and enjoy the festivals.", "3-7 days", "Costs vary based on accommodation choices and the duration of your stay.", "Carry a scarf for covering your head while visiting temples.", "Year-round, but the best time to visit is from October to March.", "Punjab is well-connected by air, with major airports in Amritsar and Chandigarh. You can also reach by train or road."));
        destinations.add(new Destination2("U.P", "Uttar Pradesh is a state known for its rich historical and cultural heritage.", R.drawable.uttarpradesh, "INR 20,000", "Explore the majestic Taj Mahal in Agra and visit the holy city of Varanasi.", "Uttar Pradesh: Hotels in the State Starting From INR 20,000", "Entry fees apply at some historical sites and religious places.", "You can find accommodations ranging from budget hotels to luxury resorts.", "Savor North Indian cuisine and street food, including chaat and kebabs.", "Visit iconic monuments, holy temples, and partake in spiritual experiences.", "5-10 days", "Costs vary based on accommodation choices and the duration of your stay.", "Carry comfortable walking shoes for temple visits.", "Best visited between October to March.", "Uttar Pradesh is well-connected by air, with major airports in Lucknow, Agra, and Varanasi. You can also reach by train or road."));
        destinations.add(new Destination2("Bihar", "Bihar is a state with a rich historical and cultural heritage, including the ruins of Nalanda and the spiritual city of Bodh Gaya.", R.drawable.bihar, "INR 15,000", "Visit Bodh Gaya, Nalanda, and explore the cultural heritage of Bihar.", "Bihar: Hotels in the State Starting From INR 15,000", "Entry fees apply at historical and religious sites.", "Accommodations are available in hotels and guesthouses.", "Enjoy regional cuisine, including litti-chokha and sweets like thekua.", "Explore ancient ruins, monasteries, and sacred Buddhist sites.", "3-7 days", "Costs vary based on accommodation choices and the duration of your stay.", "Carry comfortable walking shoes for temple visits.", "Best visited between October to March.", "The nearest airport to Bodh Gaya is Gaya Airport, and Bihar is well-connected by train and road."));
        return destinations;
    }
}
